### ISSUE TITLE
Infinite loops

### ISSUE THREAD

**Issue by MarkMCode** [MarkMegarry/VEML7700-Arduino-Library#1]
There are several functions which depend on statements like while(1). Without additional consideration, these functions are not robust and may never exit, blocking execution of the rest of the user's program. Any function with an infinite loop should have a timeout for its infinite loop. These functions should be able to indicate a timeout error state to their calling function via their return value.

**Comment by mark-mega** [comment]
Functions containing infinite loops such as while(1):
- int ALScalibrate()
- int WHITEcalibrate()
- int ALS_ITNegativeAdjust()
- int WHITE_ITNegativeAdjust()

A timer must be added to all while(1) statements which causes the function to return an error value such as -1.

**Comment by mark-mega** [comment]
Issue resolved
